#pragma once

#include <tokenizer.hpp>

namespace Lexic {
	enum struct TYPE : size_t {
		OPINC, OPDEC,
		OPASGNSHL, OPASGNSHR,
		OPSHL, OPSHR,
		OPASGNSUM, OPASGNSUB, OPASGNMUL, OPASGNDIV, OPASGNREM, OPASGNAND, OPASGNXOR, OPASGNOR,
		OPEQ, OPNEQ,
		OPLAND, OPLOR,
		OPARROW,
		OPLE, OPGE,
		OPASGN,
		OPSUM, OPSUB, OPMUL, OPDIV, OPREM,
		OPNOT, OPBNOT, OPAND, OPOR, OPXOR,
		OPLT, OPGT,
		OPCOND, OPCOLON, OPCOMMA, OPDOT,
		PAOPEN, PACLOSE, OPBRKOPEN, OPBRKCLOSE,
		NUMREAL, NUMINT, BOOLTRUE, BOOLFALSE,
		SIZEOF, IDENT,
		INVALID, COUNT
	};
	using LexicTokenizer = Tokenizer<TYPE, TYPE::INVALID, static_cast<size_t>(TYPE::COUNT)>;
	extern const LexicTokenizer tokenizer;
}
