#include <lexic.hpp>

namespace Lexic {
	using Type = LexicTokenizer::Type;

	const LexicTokenizer tokenizer{
		std::array<Type, static_cast<size_t>(TYPE::COUNT)> {
			Type{ TYPE::OPINC,		"OpIncrement",			R"(\+\+)",			false, {} },
			Type{ TYPE::OPDEC,		"OpDecrement",			R"(--)",			false, {} },
			Type{ TYPE::OPASGNSHL,	"OpAssignShiftLeft",	R"(<<=)",			false, {} },
			Type{ TYPE::OPASGNSHR,	"OpAssignShiftRight",	R"(>>=)",			false, {} },
			Type{ TYPE::OPSHL,		"OpShiftLeft",			R"(<<)",			false, {} },
			Type{ TYPE::OPSHR,		"OpShiftRight",			R"(>>)",			false, {} },
			Type{ TYPE::OPASGNSUM,	"OpAssignSum",			R"(\+=)",			false, {} },
			Type{ TYPE::OPASGNSUB,	"OpAssignSub",			R"(-=)",			false, {} },
			Type{ TYPE::OPASGNMUL,	"OpAssignMult",			R"(\*=)",			false, {} },
			Type{ TYPE::OPASGNDIV,	"OpAssignDiv",			R"(/=)",			false, {} },
			Type{ TYPE::OPASGNREM,	"OpAssignRemainder",	R"(%=)",			false, {} },
			Type{ TYPE::OPASGNAND,	"OpAssignAnd",			R"(&=)",			false, {} },
			Type{ TYPE::OPASGNXOR,	"OpAssignXor",			R"(\^=)",			false, {} },
			Type{ TYPE::OPASGNOR,	"OpAssignOr",			R"(\|=)",			false, {} },
			Type{ TYPE::OPEQ,		"OpEquals",				R"(==)",			false, {} },
			Type{ TYPE::OPNEQ,		"OpNotEquals",			R"(!=)",			false, {} },
			Type{ TYPE::OPLAND,		"OpLogicalAnd",			R"(&&)",			false, {} },
			Type{ TYPE::OPLOR,		"OpLogicalOr",			R"(\|\|)",			false, {} },
			Type{ TYPE::OPARROW,	"OpArrow",				R"(->)",			false, {} },
			Type{ TYPE::OPLE,		"OpLessOrEquals",		R"(<=)",			false, {} },
			Type{ TYPE::OPGE,		"OpGreaterOrEquals",	R"(>=)",			false, {} },
			Type{ TYPE::OPASGN,		"OpAssign",				R"(=)",				false, {} },
			Type{ TYPE::OPSUM,		"OpSum",				R"(\+)",			false, {} },
			Type{ TYPE::OPSUB,		"OpSub",				R"(-)",				false, {} },
			Type{ TYPE::OPMUL,		"OpMul",				R"(\*)",			false, {} },
			Type{ TYPE::OPDIV,		"OpDiv",				R"(/)",				false, {} },
			Type{ TYPE::OPREM,		"OpRemainder",			R"(%)",				false, {} },
			Type{ TYPE::OPNOT,		"OpNot",				R"(!)",				false, {} },
			Type{ TYPE::OPBNOT,		"OpBinaryNot",			R"(~)",				false, {} },
			Type{ TYPE::OPAND,		"OpAnd",				R"(&)",				false, {} },
			Type{ TYPE::OPOR,		"OpOr",					R"(\|)",			false, {} },
			Type{ TYPE::OPXOR,		"OpXor",				R"(\^)",			false, {} },
			Type{ TYPE::OPLT,		"OpLessThan",			R"(<)",				false, {} },
			Type{ TYPE::OPGT,		"OpGreaterThan",		R"(>)",				false, {} },
			Type{ TYPE::OPCOND,		"OpCond",				R"(\?)",			false, {} },
			Type{ TYPE::OPCOLON,	"OpColon",				R"(:)",				false, {} },
			Type{ TYPE::OPCOMMA,	"OpComma",				R"(,)",				false, {} },
			Type{ TYPE::OPDOT,		"OpDot",				R"(\.)",			false, {} },
			Type{ TYPE::OPSEMICOLON,"OpSemicolon",			R"(;)",				false, {} },
			Type{ TYPE::PAOPEN,		"ParOpen",				R"(\()",			false, {} },
			Type{ TYPE::PACLOSE,	"ParClose",				R"(\))",			false, {} },
			Type{ TYPE::OPBRKOPEN,	"BrkOpen",				R"(\[)",			false, {} },
			Type{ TYPE::OPBRKCLOSE,	"BrkClose",				R"(\])",			false, {} },
			Type{ TYPE::NUMREAL,	"NumReal",				R"(\d+\.\d+)",		true,  {} },
			Type{ TYPE::NUMINT,		"NumInt",				R"(\d+)",			true,  {} },
			Type{ TYPE::BOOLTRUE,	"BoolTrue",				R"(true|True)",		false, {} },
			Type{ TYPE::BOOLFALSE,	"BoolFalse",			R"(false|False)",	false, {} },
			Type{ TYPE::SIZEOF,		"SizeOf",				R"(sizeof)",		false, {} },
			Type{ TYPE::IDENT,		"Identifier",			R"([_A-Za-z]\w*)",	true,  {} },
			Type{ TYPE::INVALID,	"Invalid",				R"([^\s])",			false, {} },
		}
	};
}
